version: '2'

services:
     cassandra:
          container_name: cassandra
          build:
               context: .
               dockerfile: .docker/docker-cassandra.dockerfile
          ports:
               - "7000:7000"
               - "7001:7001"
               - "7199:7199"
               - "9042:9042"
               - "9160:9160"
          env_file:
               - ./.docker/env/cassandra.env
          networks:
               - seo-app-network

networks:
     seo-app-network:
          driver: bridge